[package]
name = "sni-skip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
etherparse = "0.13.0"
log = "0.4.19"
nom = "7.1.3"
